---
name: Lint Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  yamllint:
    name: YAML Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: YAML Lint Check
        uses: frenck/action-yamllint@v1
        with:
          config: "./.github/lint/yamllint.yml"
