---
name: Markdown Lint Check

on:
  pull_request:
    paths:
      - "**.md"

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v12
        with:
          config: "./.github/lint/markdownlint.yml"
          globs: "**/*.md"
