---
name: Updates README
on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'
      - name: Prepare
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          mkdir .tmp
      - uses: huantt/article-listing@v1.2.0
        with:
          username: ndrone
          template-file: "templates/blog.md.tpl"
          out-file: ".tmp/blog.md.tpl"
          limit: 5
      - uses: huantt/weather-forecast@v1.0.5
        with:
          city: Cincinnati
          days: 7
          weather-api-key: ${{ secrets.WEATHER_API_KEY }}
          template-file: 'templates/weather.md.tpl'
          out-file: '.tmp/weather.md.tpl'
      - run: |
          cat .tmp/blog.md.tpl
          cat .tmp/weather.md.tpl
      - name: Merge templates
        run: |
          go install github.com/huantt/merge-templates@v1.0.0
          merge-templates README.md 'templates/README.md.tpl' '.tmp/blog.md.tpl' '.tmp/weather.md.tpl'
      - run: rm -rf .tmp
      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Updates README with blog and weather"
          title: "Updates README with blog and weather"
